name = "seakeeping"
version = "2.3.20230518"
license = "BSD-3-Clause"
author = "左志华"
maintainer = "左志华（zuo.zhihua@qq.com）"
copyright = "Copyright 2022, 左志华"
description = "Seakeeping Routines for Naval Architecture and Ocean Engineering"

[install]
library = true

[fortran]
implicit-external = true
