name = "seakeeping"
version = "1.6.0"
license = "BSD-3-Clause"
author = "左志华"
maintainer = "左志华（zuo.zhihua@qq.com）"
copyright = "Copyright 2022, 左志华"
description = "Seakeeping Routines for Naval Architecture and Ocean Engineering"

[build]
auto-tests = true
auto-examples = true
link = 'openblas'

[install]
library = true
