name = "seakeeping"
version = "2.5.20230611"
license = "BSD-3-Clause"
author = "左志华"
maintainer = "左志华（zuo.zhihua@qq.com）"
copyright = "Copyright 2022~2023, 左志华"
description = "Seakeeping Routines for Naval Architecture and Ocean Engineering"

[install]
library = true

[fortran]
implicit-external = true

[dev-dependencies]
test-drive = { git='https://gitee.com/fortran-base/test-drive', tag='v0.4.0' }
